config/routes.rb
OmniauthDeviseExample::Application.routes.draw do
  resources :monkeys

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

  root :to => "monkeys#index"

end

app/models/monkey.rb
class Monkey < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_tokens
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session[:omniauth]
        user.user_tokens.build(:provider => data['provider'], :uid => data['uid'])
      end
    end
  end
  
  def apply_omniauth(omniauth)
    #add some info about the user
    #self.name = omniauth['user_info']['name'] if name.blank?
    #self.nickname = omniauth['user_info']['nickname'] if nickname.blank?
    
    unless omniauth['credentials'].blank?
      user_tokens.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
      #user_tokens.build(:provider => omniauth['provider'], 
      #                  :uid => omniauth['uid'],
      #                  :token => omniauth['credentials']['token'], 
      #                  :secret => omniauth['credentials']['secret'])
    else
      user_tokens.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
    end
    #self.confirm!# unless user.email.blank?
  end
  
  def password_required?
    (user_tokens.empty? || !password.blank?) && super  
  end
end

app/models/user_token.rb
class UserToken < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  # GET /monkeys
  # GET /monkeys.xml
  def index
    @monkeys = Monkey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @monkeys }
    end
  end

  # GET /monkeys/1
  # GET /monkeys/1.xml
  def show
    @monkey = Monkey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @monkey }
    end
  end

  # GET /monkeys/new
  # GET /monkeys/new.xml
  def new
    @monkey = Monkey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @monkey }
    end
  end

  # GET /monkeys/1/edit
  def edit
    @monkey = Monkey.find(params[:id])
  end

  # POST /monkeys
  # POST /monkeys.xml
  def create
    @monkey = Monkey.new(params[:monkey])

    respond_to do |format|
      if @monkey.save
        format.html { redirect_to(@monkey, :notice => 'Monkey was successfully created.') }
        format.xml  { render :xml => @monkey, :status => :created, :location => @monkey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @monkey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /monkeys/1
  # PUT /monkeys/1.xml
  def update
    @monkey = Monkey.find(params[:id])

    respond_to do |format|
      if @monkey.update_attributes(params[:monkey])
        format.html { redirect_to(@monkey, :notice => 'Monkey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @monkey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /monkeys/1
  # DELETE /monkeys/1.xml
  def destroy
    @monkey = Monkey.find(params[:id])
    @monkey.destroy

    respond_to do |format|
      format.html { redirect_to(monkeys_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def method_missing(provider)
    if !User.omniauth_providers.index(provider).nil?
      #omniauth = request.env["omniauth.auth"]
      omniauth = env["omniauth.auth"]
    
      if current_user #or User.find_by_email(auth.recursive_find_by_key("email"))
        current_user.user_tokens.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
         flash[:notice] = "Authentication successful"
         redirect_to edit_user_registration_path
      else
    
      authentication = UserToken.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
   
        if authentication
          flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => omniauth['provider']
          sign_in_and_redirect(:user, authentication.user)
          #sign_in_and_redirect(authentication.user, :event => :authentication)
        else
          
          #create a new user
          unless omniauth.recursive_find_by_key("email").blank?
            user = User.find_or_initialize_by_email(:email => omniauth.recursive_find_by_key("email"))
          else
            user = User.new
          end
          
          user.apply_omniauth(omniauth)
          #user.confirm! #unless user.email.blank?

          if user.save
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => omniauth['provider'] 
            sign_in_and_redirect(:user, user)
          else
            session[:omniauth] = omniauth.except('extra')
            redirect_to new_user_registration_url
          end
        end
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniauthDeviseExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<div id="user_nav">
	  <% if user_signed_in? %>
	    Signed in as <%= current_user.email %>. Not you?
	    <%= link_to "Sign out", destroy_user_session_path %>
	  <% else %>
	    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>
	</div>

<%= yield %>

</body>
</html>

app/views/monkeys/_form.html.erb
<%= form_for(@monkey) do |f| %>
  <% if @monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% @monkey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing monkey</h1>

<%= render 'form' %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<h1>Listing monkeys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @monkeys.each do |monkey| %>
  <tr>
    <td><%= monkey.name %></td>
    <td><%= monkey.desc %></td>
    <td><%= link_to 'Show', monkey %></td>
    <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
    <td><%= link_to 'Destroy', monkey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New monkey</h1>

<%= render 'form' %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @monkey.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @monkey.desc %>
</p>


<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>